services:
  webapi:
    image: webapi
    build:
      context: .
      dockerfile: WebApi/Dockerfile

  webclient:
    image: webclient
    build:
      context: .
      dockerfile: WebClient/Dockerfile

